workflows:
  nexplay-x-debug:
    name: NexPlay X Debug Build
    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Checkout
        script: |
          git clone $CM_REPO_URL .
      
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Setup local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk
